name: gabriel_malakias
description: "About programming related topics and experiences I want to share"
bio: "A brazilian trying to navigate in foreign lands"
meta_description: "About programming related topics and experiences I want to share"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
domain_name: 'gabrielmalakias.com.br'
google_analytics: 'UA-87321020-1'
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

url: 'https://gabrielmalakias.com.br'
author: 'Gabriel Malaquias'
