name: gabriel_malakias
description: "About programming and things that I'm trying to learn"
bio: "I'm a tech explorer, currently using Ruby and trying to learn many things."
meta_description: "About programming and things that I'm trying to learn"


markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://gabrielmalakias.github.io'
google_analytics: 'UA-87321020-1'
gems: [jekyll-paginate]

url:            'https://gabrielmalakias.github.io'
author:         'Gabriel Malaquias'
