name: gabriel_malakias
description: "About programming related topics and experiences I want to share"
bio: "I'm a tech explorer, currently using Ruby and trying to learn many things."
meta_description: "About programming related topics and experiences I want to share"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 5
baseurl: /
domain_name: 'gabrielmalakias.com.br'
google_analytics: 'UA-87321020-1'
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-sitemap]

url: 'http://gabrielmalakias.com.br'
author: 'Gabriel Malaquias'
