name: gabriel_malakias
description: About programming and things that im trying to learn
meta_description: "About programming and things that im trying to learn"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://gabrielmalakias.github.io'
google_analytics: 'UA-87321020-1'
gems: [jekyll-paginate]

url:            'https://gabrielmalakias.github.io'
author:         'Gabriel Malaquias'
